// ESLint flat config — server (@devdigest/api). Run: `pnpm lint` (CI: `pnpm exec eslint .`).
// Not type-aware (fast, no tsconfig project). Rules that already fire on the
// existing code start as warnings; tighten them one at a time.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "clones/**",
      // Generated by drizzle-kit — never edited by hand (see root CLAUDE.md "Do not touch").
      "src/db/migrations/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": "warn",
      "prefer-const": "warn",
    },
  },
);
