// ESLint flat config — server (@devdigest/api). Run: `pnpm lint` (CI: `pnpm exec eslint .`).
// Not type-aware (fast, no tsconfig project). Rules that already fire on the
// existing code start as warnings; tighten them one at a time.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "clones/**",
      // Generated by drizzle-kit — never edited by hand (see root AGENTS.md "Do not touch").
      "src/db/migrations/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "no-empty": "warn",
      "prefer-const": "warn",
    },
  },
  // ---- Onion rings (.claude/skills/onion-architecture/SKILL.md) ----
  // The fast, in-editor half of the boundary checks; the full import-graph rules
  // live in .dependency-cruiser.cjs (`pnpm arch`). These are `error`, not `warn`,
  // on purpose: the existing warning baseline is load-bearing for spotting
  // regressions (server/INSIGHTS.md, 2026-09-18).
  {
    files: ["src/modules/*/routes.ts"],
    ignores: [
      // Known deviations — no service layer yet (SKILL.md §11, deviation 1).
      "src/modules/pulls/routes.ts",
      "src/modules/polling/routes.ts",
      "src/modules/workspace/routes.ts",
      "src/modules/settings/routes.ts",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["drizzle-orm", "drizzle-orm/*", "**/db/schema", "**/db/schema.js"],
              message:
                "routes.ts is transport only — move the query into repository/<entity>.repo.ts (onion-architecture SKILL.md §5).",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["src/modules/*/service.ts", "src/modules/*/run-executor.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["octokit", "openai", "@anthropic-ai/*", "simple-git", "@ast-grep/*"],
              message:
                "Services reach external systems through a container port, never a vendor SDK. No port yet? Add one (onion-architecture SKILL.md §6).",
            },
            {
              group: ["drizzle-orm", "drizzle-orm/*"],
              message:
                "Services never write SQL — persistence goes through the module's repository (onion-architecture SKILL.md §4).",
            },
          ],
        },
      ],
    },
  },
);
