import type { CSSProperties } from "react";

export const s = {
  box: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    marginBottom: 18,
  } satisfies CSSProperties,
  controls: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  staleHint: {
    fontSize: 12,
    color: "var(--warning)",
  } satisfies CSSProperties,
  summary: {
    fontSize: 13.5,
    color: "var(--text-primary)",
    margin: "0 0 14px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  sectionHeading: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "var(--text-tertiary, var(--text-secondary))",
    margin: "14px 0 8px",
  } satisfies CSSProperties,
  noRisks: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: 0,
  } satisfies CSSProperties,
  missingList: {
    listStyle: "none",
    margin: "0 0 14px",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  missingItem: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  riskList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  riskRow: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
  } satisfies CSSProperties,
  riskHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    font: "inherit",
    color: "inherit",
    padding: 0,
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
  } satisfies CSSProperties,
  severityBadge: {
    fontSize: 11.5,
    fontWeight: 600,
  } satisfies CSSProperties,
  riskToggle: {
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskRefs: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 6,
  } satisfies CSSProperties,
  riskRef: {
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskExplanation: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    margin: "8px 0 0",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  focusRow: {} satisfies CSSProperties,
  focusButton: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    cursor: "pointer",
    textAlign: "left",
    font: "inherit",
    color: "inherit",
    padding: "7px 10px",
  } satisfies CSSProperties,
  focusFile: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  focusReason: {
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
