import type { CSSProperties } from "react";

/** Co-located styles for SeverityCounts + FindingsPopover. */
export const s = {
  counts: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    flexWrap: "wrap",
    borderRadius: 5,
    cursor: "default",
    outlineOffset: 2,
  } satisfies CSSProperties,
  // Fixed + portalled so list/row containers can't clip it; anchored to the
  // trigger's viewport rect (below it, or above via `bottom` when out of room).
  card: (p: { top?: number; bottom?: number; left: number }): CSSProperties => ({
    position: "fixed",
    top: p.top,
    bottom: p.bottom,
    left: p.left,
    zIndex: 60,
    width: 400,
    maxHeight: 340,
    overflowY: "auto",
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    boxShadow: "0 12px 32px rgba(0,0,0,.45)",
    cursor: "default",
    textAlign: "left",
  }),
  title: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  // Read-only preview row (no hover affordance: nothing here is clickable).
  item: {
    display: "block",
    width: "100%",
    padding: "8px 0",
    borderTop: "1px solid var(--border)",
    textAlign: "left",
    cursor: "default",
  } satisfies CSSProperties,
  head: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  itemTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 3,
    fontSize: 12,
  } satisfies CSSProperties,
  location: { color: "var(--accent)" } satisfies CSSProperties,
  rationale: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  status: { fontSize: 12, color: "var(--text-muted)", padding: "4px 0" } satisfies CSSProperties,
} as const;
