import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillModal. */
export const s = {
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,
  dropZone: (hot: boolean): CSSProperties => ({
    border: "1.5px dashed " + (hot ? "var(--accent)" : "var(--border-strong)"),
    background: hot ? "var(--accent-bg)" : "var(--bg-surface)",
    borderRadius: 10,
    padding: "32px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    textAlign: "center",
    color: "var(--text-secondary)",
    fontSize: 14,
  }),
  hiddenInput: { display: "none" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 7,
    padding: "10px 12px",
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  warningIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  warningTitle: { fontWeight: 700, marginBottom: 2 } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  description: { fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  bodyBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    padding: "14px 18px",
    maxHeight: 280,
    overflow: "auto",
    fontSize: 14,
  } satisfies CSSProperties,
  ignoredList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  ignoredRow: (exec: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 13,
    background: exec ? "var(--crit-bg)" : "var(--bg-surface)",
    color: exec ? "var(--crit)" : "var(--text-secondary)",
  }),
  ignoredPath: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  fieldError: { fontSize: 12, color: "var(--crit)", marginTop: 6 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
} as const;
